name: Keep Streamlit Apps Awake

on:
  schedule:
    - cron: "0 */10 * * *"
  workflow_dispatch:

jobs:
  empty-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Create empty commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit --allow-empty -m "Keep Streamlit apps awake"
          git push